/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATypographyTitle: typeof import('@arco-design/web-vue')['TypographyTitle']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
